package graphique;

import projet_java.GestionReservation;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lucie
 */
public class menuagent extends javax.swing.JFrame {

    private GestionReservation gr;
    /**
     * Creates new form menuagent
     */
    public menuagent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        gestionvol = new javax.swing.JMenu();
        creervol = new javax.swing.JMenuItem();
        creerdestination = new javax.swing.JMenuItem();
        supprimervol = new javax.swing.JMenuItem();
        afficherreservationpourvol = new javax.swing.JMenuItem();
        gestionresa = new javax.swing.JMenu();
        associerpassagerresa = new javax.swing.JMenuItem();
        relancerresa = new javax.swing.JMenuItem();
        supprimerresa = new javax.swing.JMenuItem();
        rechercheresa = new javax.swing.JMenuItem();
        montantresaperiode = new javax.swing.JMenuItem();
        montantresavol = new javax.swing.JMenuItem();
        montantresadestination = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Menu agent", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 11), new java.awt.Color(0, 51, 102))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel1.setText("Bonjour + nom + prénom");

        jButton1.setText("Quitter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Créer un vol ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Créer un Aéroport");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(20, 20, 20))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        gestionvol.setText("Gestion des vols");

        creervol.setText("Créer des vols");
        creervol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creervolActionPerformed(evt);
            }
        });
        gestionvol.add(creervol);

        creerdestination.setText("Créer une destination");
        creerdestination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creerdestinationActionPerformed(evt);
            }
        });
        gestionvol.add(creerdestination);

        supprimervol.setText("Supprimer un vol");
        supprimervol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimervolActionPerformed(evt);
            }
        });
        gestionvol.add(supprimervol);

        afficherreservationpourvol.setText("Afficher les réservations pour un vol donné");
        gestionvol.add(afficherreservationpourvol);

        jMenuBar1.add(gestionvol);

        gestionresa.setText("Gestion des réservations");

        associerpassagerresa.setText("Associer un passager à une réservation");
        gestionresa.add(associerpassagerresa);

        relancerresa.setText("Relancer une réservation");
        gestionresa.add(relancerresa);

        supprimerresa.setText("Supprimer une réservation");
        gestionresa.add(supprimerresa);

        rechercheresa.setText("Rechercher une réservation");
        gestionresa.add(rechercheresa);

        montantresaperiode.setText("Montant des réservations pour une période donnée");
        gestionresa.add(montantresaperiode);

        montantresavol.setText("Montant des réservations pour un vol donné");
        gestionresa.add(montantresavol);

        montantresadestination.setText("Montant des réservations pour une destination donnée");
        gestionresa.add(montantresadestination);

        jMenuBar1.add(gestionresa);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void creervolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creervolActionPerformed
        creervol cv = new creervol(gr);
        cv.setVisible(true);    }//GEN-LAST:event_creervolActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        creervol cv = new creervol(gr);
        cv.setVisible(true);     }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        creeraeroport ca = new creeraeroport(gr);
        ca.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void creerdestinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creerdestinationActionPerformed
        creeraeroport ca = new creeraeroport(gr);
        ca.setVisible(true);
    }//GEN-LAST:event_creerdestinationActionPerformed

    private void supprimervolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimervolActionPerformed
        supprimervol sv = new supprimervol(gr);
        sv.setVisible(true);    }//GEN-LAST:event_supprimervolActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuagent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuagent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuagent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuagent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuagent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem afficherreservationpourvol;
    private javax.swing.JMenuItem associerpassagerresa;
    private javax.swing.JMenuItem creerdestination;
    private javax.swing.JMenuItem creervol;
    private javax.swing.JMenu gestionresa;
    private javax.swing.JMenu gestionvol;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem montantresadestination;
    private javax.swing.JMenuItem montantresaperiode;
    private javax.swing.JMenuItem montantresavol;
    private javax.swing.JMenuItem rechercheresa;
    private javax.swing.JMenuItem relancerresa;
    private javax.swing.JMenuItem supprimerresa;
    private javax.swing.JMenuItem supprimervol;
    // End of variables declaration//GEN-END:variables
}
